a <- as.numeric(readline("Enter first number: "))
b <- as.numeric(readline("Enter second number: "))
print(a + b)
print(a - b)
print(a * b)
print(a / b)
vec1 <- c(a + b, a - b, a * b, a / b)
print(vec1)
print("using list:")
list1 <- list(add = a + b, sub = a - b, mul = a * b, div = a / b)
print(list1)
df1 <- data.frame ( c("Addition" , "Subtraction", "Multiplication", "Division") ,
                   Result = c(a + b, a - b, a * b, a / b))
print(df1)